support checksum

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -81,7 +81,14 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Setup mise
+        id: bad
         uses: ./
         with:
           version: 2024.9.6
           sha256: 1f0b8c3d2e4f5a6b7c8d9e0f1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t
+      - name: expect failure
+        run: echo "Failed as expected"
+        if: job.steps.bad.status == failure()
+      - name: not failed as expected
+        run: exit 1
+        if: job.steps.bad.status == success()
